// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TrixController from "./trix_controller"
import ChatController from "./chat_controller"
import SearchController from "./search_controller"

application.register("trix", TrixController)
application.register("chat", ChatController)
application.register("search", SearchController)
